[package]
name = "rust-ws-chat"
version = "0.1.0"
authors = ["Luke Konopka <luke@lukekonopka.pl>"]
edition = "2018"

[dependencies]
ws = "0.8.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
serde_derive = "1.0.89"